name: Test by pytest

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out and cache model-zoo
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          repository: sophgo/model-zoo
          include: "dataset,vision/detection/yolov5"
          exclude: ""
      - name: Install model-zoo requirements
        run: |
          [ -f requirements.txt ] && python3 -m pip install -r requirements.txt
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: tpu-perf
      - name: build tpu-perf
        run: |
          tpu-perf/.github/workflows/pytest.sh build
      - name: Download dataset
        run: |
          tpu-perf/.github/workflows/pytest.sh dataset
      - name: Set up the nntc env and test
        run: |
          tpu-perf/.github/workflows/pytest.sh nntc
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: output/yolov5*/*.log
      - name: Set up the mlir env and test
        run: |
          tpu-perf/.github/workflows/pytest.sh mlir
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: output/yolov5*/*.log